transpiler:
  build: .
  volumes_from:
    - data
  # typescript should watch the src directory
  command: tsc -w

server:
  build: .
  volumes_from:
    - data
  # nodemon should watch the dist directory
  command: nodemon build/trade.js -w build/

data:
  build: .
  volumes:
    - .:/app            # share your code with the containers
    - /app/build         # container has its own dist directory
    - /app/node_modules # container has its own node_modules directory
  command: echo 'ok'